# Generated by Django 3.1.7 on 2021-03-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('ufname', models.CharField(max_length=30)),
                ('ulname', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('uaddress', models.TextField()),
                ('umobile', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='null', upload_to='static/products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swan.category')),
            ],
        ),
    ]
