# Generated by Django 3.1.7 on 2021-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swan', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='orders',
            name='mobile',
            field=models.CharField(default='', max_length=50),
        ),
    ]
