# Generated by Django 3.1.7 on 2021-03-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swan', '0004_auto_20210306_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
